### ISSUE TITLE
No constructor found for widget ArcGIS.widget.ArcGIS

### ISSUE THREAD

**Issue by JenniferLeeTaylor** [ivosturm/ArcGIS#1]
We are using the ArcGIS widget in our project. When we deploy the application to the Mendix cloud, we get an error message: No constructor found for widget ArcGIS.widget.ArcGIS. Locally the ArcGIS widget works if we uncheck the 'bundle widgets' option in the project settings. Has anyone else encountered this? How can we resolve? Thanks!

**Comment by ivosturm** [comment]
Hi Jennifer,

Can I have a bit more context? In what Modeler version + scenario (database, XPath, datasource microflow, etc) are you using this widget? Some printscreens of the Mendix pages + widget settings could help as well.

**Comment by JenniferLeeTaylor** [comment]
Hello Ivo,

Thank you so much for your quick response!

We are using the ArcGIS widget in Modeler version 7.19.1. We are currently using XPATH to drill down to one mail box on a map. We are using ESRI base maps. As you can see below, when the ‘Bundle widgets when running locally’ is turned off in the local version, the widget works. However, when you deploy to the cloud, the widgets are automatically bundled, so it doesn’t work. Also, if you check ‘Bundle widgets when running locally’, then the widget does not work locally and you get the same error message. Also, we have the widget working in a blank app, and we don’t get the error there, so it seems to be some kind of conflict, possibly with another widget in our larger app. I have also included screen shots from the configuration of the widget, but I have blacked out possibly sensitive information. Thanks!!

[cid:image007.png@01D4914E.8DD7BE30]

Local
[cid:image001.png@01D4914D.96DA5F70]


Cloud
[cid:image002.png@01D4914D.96DA5F70]


Widget Settings
[cid:image003.png@01D4914D.F59EEE90]



[cid:image004.png@01D4914D.F59EEE90]

[cid:image005.png@01D4914D.F59EEE90]

[cid:image006.png@01D4914D.F59EEE90]


[cid:image008.png@01D4914E.8DD7BE30]

[cid:image009.png@01D4914E.8DD7BE30]

-Jen

Jennifer Taylor
Service Support Analyst, Application Management
Innovapost
Phone: 613.221.3475

jennifer.schenk@innovapost.com<mailto:jennifer.schenk@innovapost.com%0d>
www.innovapost.com<http://www.innovapost.com/>

This e-mail may be privileged and/or confidential, and the sender does not waive any related rights and obligations. Any distribution, use or copying of this e-mail or the information it contains by other than an intended recipient is unauthorized. If you received this e-mail in error, please advise me (by return e-mail or otherwise) immediately.

**Comment by JenniferLeeTaylor** [comment]
Hi Jen and Ivo,


I tried to run the demo project locally with the 'Bundle widgets' enabled, and it also gives the same errror.

Meaning that it doesn't have anything to do with other widgets in our project.



Regards,

Seb

________________________________
From: Jennifer Schenk
Sent: 11 December 2018 12:39
To: ivosturm/ArcGIS; ivosturm/ArcGIS
Cc: Author; Sebastiaan van der Plaat
Subject: RE: [ivosturm/ArcGIS] No constructor found for widget ArcGIS.widget.ArcGIS (#1)

Hello Ivo,

Thank you so much for your quick response!

We are using the ArcGIS widget in Modeler version 7.19.1. We are currently using XPATH to drill down to one mail box on a map. We are using ESRI base maps. As you can see below, when the 'Bundle widgets when running locally' is turned off in the local version, the widget works. However, when you deploy to the cloud, the widgets are automatically bundled, so it doesn't work. Also, if you check 'Bundle widgets when running locally', then the widget does not work locally and you get the same error message. Also, we have the widget working in a blank app, and we don't get the error there, so it seems to be some kind of conflict, possibly with another widget in our larger app. I have also included screen shots from the configuration of the widget, but I have blacked out possibly sensitive information. Thanks!!

[cid:image007.png@01D4914E.8DD7BE30]

Local
[cid:image001.png@01D4914D.96DA5F70]


Cloud
[cid:image002.png@01D4914D.96DA5F70]


Widget Settings
[cid:image003.png@01D4914D.F59EEE90]



[cid:image004.png@01D4914D.F59EEE90]

[cid:image005.png@01D4914D.F59EEE90]

[cid:image006.png@01D4914D.F59EEE90]


[cid:image008.png@01D4914E.8DD7BE30]

[cid:image009.png@01D4914E.8DD7BE30]

-Jen

Jennifer Taylor
Service Support Analyst, Application Management
Innovapost
Phone: 613.221.3475

jennifer.schenk@innovapost.com<mailto:jennifer.schenk@innovapost.com%0d>
www.innovapost.com<http://www.innovapost.com/>

This e-mail may be privileged and/or confidential, and the sender does not waive any related rights and obligations. Any distribution, use or copying of this e-mail or the information it contains by other than an intended recipient is unauthorized. If you received this e-mail in error, please advise me (by return e-mail or otherwise) immediately.

**Comment by JenniferLeeTaylor** [comment]
Now that we're chatting anyway, @Ivo ...we have some feature requests :-)


1. Can there be a toggle in the widget that hides/displays the map/satellite toggle and/or the search bar

2. Can the widget be made translatable?



Cheers!

Seb



________________________________

**Comment by ivosturm** [comment]
I just released a new version (1.2.0) of the **widget** in the AppStore. Tested in Mendix 7.16.0 and with/without 'Bundle widgets when running locally' ticked, the app and widget ran smoothly. Can you confirm? If so, I will update the demo project as well.

**Comment by ivosturm** [comment]
And about the new requirements:

- The Search bar can already be disabled/enabled as a widget setting. Or do you mean front-end by an end user? For the satellite/street switch this feature is not there yet.
- Translatable; If I have some time I will check. Which labels do you need to be translatable specifically?

**Comment by JenniferLeeTaylor** [comment]
Hi Ivo,


The widget works now. Thanks for the quick response!


A few things we changed are:


1. The object ID: Only an integer is allowed here. We changed it to a String

2. The search box, when turning it off in the widget, it errors. We made a quick fix by updating the styling to "display: none;"

3. The map/satellite view toggle. We don't want to see that, so we also set the div to "display: none;"


Thanks a lot!



Regards,



Seb

________________________________

**Comment by ivosturm** [comment]
I will implement below changes somewhere in the next weeks and will let you know! Please upvote the widget if you like it 😊.

Kind regards,
Ivo

Van: JenniferLeeTaylor <notifications@github.com>
Verzonden: vrijdag 14 december 2018 02:00
Aan: ivosturm/ArcGIS <ArcGIS@noreply.github.com>
CC: Ivo Sturm <ivo.sturm@firstconsulting.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [ivosturm/ArcGIS] No constructor found for widget ArcGIS.widget.ArcGIS (#1)

Hi Ivo,


The widget works now. Thanks for the quick response!


A few things we changed are:


1. The object ID: Only an integer is allowed here. We changed it to a String

2. The search box, when turning it off in the widget, it errors. We made a quick fix by updating the styling to "display: none;"

3. The map/satellite view toggle. We don't want to see that, so we also set the div to "display: none;"


Thanks a lot!



Regards,



Seb

________________________________

**Comment by JenniferLeeTaylor** [comment]
Hi Ivo,


Our next step for the widget is to make it available offline. Is this by any chance also on your future plans for the widget? If it is not, we are happy to contribute. Please let us know


Happy Friday!


Regards,

Seb

________________________________

**Comment by ivosturm** [comment]
Hi Jennifer,

No it is not. Please share any contribution if you get this working. I am happy to help with any questions you would have. The widget is fairly complex in terms of size, so I can understand some questions will pop-up along the road.

Good luck!

Kind regards,
Ivo

Van: JenniferLeeTaylor <notifications@github.com>
Verzonden: vrijdag 14 december 2018 16:10
Aan: ivosturm/ArcGIS <ArcGIS@noreply.github.com>
CC: Ivo Sturm <ivo.sturm@firstconsulting.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [ivosturm/ArcGIS] No constructor found for widget ArcGIS.widget.ArcGIS (#1)

Hi Ivo,


Our next step for the widget is to make it available offline. Is this by any chance also on your future plans for the widget? If it is not, we are happy to contribute. Please let us know


Happy Friday!


Regards,

Seb

________________________________

**Comment by JenniferLeeTaylor** [comment]
Thanks Ivo!

We will be working more on the offline maps in January, so we may email you again then. In the meantime, have a great holiday season!

-Jen

Jennifer Taylor
Service Support Analyst, Application Management
Innovapost
Phone: 613.221.3475

jennifer.schenk@innovapost.com<mailto:jennifer.schenk@innovapost.com%0d>
www.innovapost.com<http://www.innovapost.com/>

This e-mail may be privileged and/or confidential, and the sender does not waive any related rights and obligations. Any distribution, use or copying of this e-mail or the information it contains by other than an intended recipient is unauthorized. If you received this e-mail in error, please advise me (by return e-mail or otherwise) immediately.

**Comment by ivosturm** [comment]
Solved
